// Paradox Evolution (custom addition, see DATA_NOTES.md "Custom additions"):
// a Pokémon holding Paradoxorb-A or Paradoxorb-F turns into its Ancient or
// Future Paradox form (the Gen 9 Paradox Pokémon based on it) the first time
// it's sent out, and stays that way for the rest of the battle. paradox.json is
// generated by scripts/build-paradox-data.mjs. No simulator imports: the UI
// thread and the worker both build their data from this.
import paradoxData from './paradox.json';
import type { SpriteAvailability } from '../champions';

export type ParadoxKind = 'ancient' | 'future';

export interface ParadoxForm {
  /** The Paradox Pokémon, e.g. "Great Tusk". */
  form: string;
  kind: ParadoxKind;
  /** The Sun & Moon Pokémon that turn into it. */
  bases: string[];
}

export const PARADOX_FORMS = paradoxData.forms as ParadoxForm[];
/** Gen 8-9 moves the Paradox forms learn (made available for them only). */
export const PARADOX_MOVES = paradoxData.moves;
export const PARADOX_SPRITES = paradoxData.sprites as unknown as Record<string, SpriteAvailability>;

export const PARADOX_ITEMS: Record<ParadoxKind, string> = { ancient: 'Paradoxorb-A', future: 'Paradoxorb-F' };
export const PARADOX_ABILITIES: Record<ParadoxKind, string> = { ancient: 'Protosynthesis', future: 'Quark Drive' };
export const PARADOX_LABELS: Record<ParadoxKind, string> = { ancient: 'Ancient', future: 'Future' };

const toId = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

export const PARADOX_MOVE_IDS = new Set(PARADOX_MOVES.map(toId));
const ITEM_KIND = new Map<string, ParadoxKind>(Object.entries(PARADOX_ITEMS).map(([kind, item]) => [toId(item), kind as ParadoxKind]));
const FORM_KIND = new Map(PARADOX_FORMS.map(f => [f.form, f.kind]));
const FORM_BY_BASE = new Map(PARADOX_FORMS.flatMap(f => f.bases.map(b => [`${f.kind}:${toId(b)}`, f.form] as const)));

/** The Paradox kind a Paradoxorb item gives (null for any other item). */
export const paradoxKindOfItem = (item: string | undefined | null): ParadoxKind | null => ITEM_KIND.get(toId(item ?? '')) ?? null;
/** Whether a species name is one of the Paradox forms (Paradox Evolution only; not a team choice). */
export const isParadoxForm = (species: string) => FORM_KIND.has(species);
/** Ancient or Future, for a Paradox form's name. */
export const paradoxKindOfForm = (species: string): ParadoxKind | null => FORM_KIND.get(species) ?? null;
/** The species' Paradox form of that kind, if it has one. */
export const paradoxFormOf = (species: string, kind: ParadoxKind): string | null => FORM_BY_BASE.get(`${kind}:${toId(species)}`) ?? null;
/** What a set Paradox Evolves into in battle (null without a matching Paradoxorb). */
export function paradoxFormForSet(species: string, item: string | undefined | null): string | null {
  const kind = paradoxKindOfItem(item);
  return kind ? paradoxFormOf(species, kind) : null;
}
/** Whether the species may hold this item: Paradoxorbs only go on Pokémon with that kind of Paradox form. */
export function canHoldItem(species: string, item: string): boolean {
  const kind = paradoxKindOfItem(item);
  return !kind || !!paradoxFormOf(species, kind);
}

const ABILITY_DESC = 'Raises this Pokemon\'s highest stat (not HP) by 1.3x, or Speed by 1.5x, while it is on the field. Ties go Atk > Def > SpA > SpD > Spe. Not a stat stage; no weather or terrain needed.';

/**
 * Data layered on the Gen 7 mod data: the two Paradoxorbs, the custom
 * Protosynthesis / Quark Drive, and the Gen 8-9 moves the Paradox forms learn.
 * `ui` also makes the Paradox species themselves visible (stats, types and
 * sprites for the team builder and battle display); the simulator keeps them
 * "Future" so they can't be picked as team members, only reached by Paradox
 * Evolution.
 */
export function paradoxOverrides({ ui }: { ui: boolean }): Record<string, Record<string, object>> {
  const items: Record<string, object> = {};
  let num = 10102;
  for (const kind of ['ancient', 'future'] as const) {
    const name = PARADOX_ITEMS[kind];
    const users = PARADOX_FORMS.filter(f => f.kind === kind).flatMap(f => f.bases);
    const desc = `If held by a Pokemon with an ${PARADOX_LABELS[kind]} Paradox Form, it Paradox Evolves the first time it is sent out and stays that way for the battle.`;
    items[toId(name)] = { name, num: num++, gen: 7, isNonstandard: null, itemUser: users, shortDesc: desc, desc };
  }
  const abilities: Record<string, object> = {};
  num = 10120;
  for (const kind of ['ancient', 'future'] as const) {
    const name = PARADOX_ABILITIES[kind];
    abilities[toId(name)] = {
      name, num: num++, gen: 7, isNonstandard: null, rating: 3,
      flags: { failroleplay: 1, noreceiver: 1, noentrain: 1, notrace: 1, failskillswap: 1, notransform: 1 },
      shortDesc: ABILITY_DESC, desc: ABILITY_DESC,
    };
  }
  const moves = Object.fromEntries(PARADOX_MOVES.map(n => [toId(n), { inherit: true, gen: 7, isNonstandard: null }]));
  const conditions = { paradoxevolution: { name: 'Paradox Evolution' } };
  if (!ui) return { Items: items, Abilities: abilities, Moves: moves, Conditions: conditions };
  // "Future" comes from the entry's generation, so it has to say Gen 7 (as for the Champions Pokémon).
  const species = Object.fromEntries(PARADOX_FORMS.map(f => [toId(f.form), { inherit: true, gen: 7, isNonstandard: null }]));
  const formatsData = Object.fromEntries(PARADOX_FORMS.map(f => [toId(f.form), { isNonstandard: null, tier: 'OU' }]));
  return { Items: items, Abilities: abilities, Moves: moves, Species: species, FormatsData: formatsData };
}
