// Pokémon Champions additions: Mega Evolutions introduced after Sun & Moon
// (Legends: Z-A and its DLC) that are in Pokémon Champions, made legal in this
// app on request. Sourced data: megas.json (Serebii's Champions Pokédex);
// derived.json is generated by scripts/build-champions-data.mjs.
// No simulator imports: the UI thread and the worker both build their data from this.
import derivedData from './derived.json';
import megasData from './megas.json';

type StatID = 'hp' | 'atk' | 'def' | 'spa' | 'spd' | 'spe';

export interface ChampionsMega {
  /** Showdown forme name, e.g. "Lucario-Mega-Z". */
  species: string;
  megaStone: string;
  types: string[];
  ability: string;
  baseStats: Record<StatID, number>;
  source: string;
}

export interface SpriteAvailability {
  /** Showdown sprite id (file name without extension). */
  id: string;
  /** [width, height] when the file exists on the sprite server, else null. */
  ani: [number, number] | null;
  aniBack: [number, number] | null;
  gen5: [number, number] | null;
  gen5Back: [number, number] | null;
}

export const CHAMPIONS_MEGAS = megasData.megas as ChampionsMega[];
export const CHAMPIONS_STONES = [...new Set(CHAMPIONS_MEGAS.map(m => m.megaStone))];
/** Base Pokémon from Gen 8-9 that are allowed for their Champions Megas (approved decision). */
export const NEW_BASE_SPECIES = derivedData.newBaseSpecies;
/** Formes that exist in Gen 7 data but weren't obtainable in Sun & Moon, unlocked for a Champions Mega. */
export const UNLOCKED_FORMES = derivedData.unlockedFormes;
/** Moves that the new base Pokémon and unlocked formes learn but Gen 7 marks unavailable (Gen 8-9 moves, Light of Ruin). */
export const NEW_MOVES = derivedData.moves;
/** Abilities from Gen 8-9 used by the new base Pokémon and the Champions Megas. */
export const NEW_ABILITIES = derivedData.abilities;
export const CHAMPIONS_SPRITES = derivedData.sprites as unknown as Record<string, SpriteAvailability>;

const toId = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

/** Moves only the Champions Pokémon may use (anyone else, Smeargle's Sketch included, still can't). */
export const NEW_MOVE_IDS = new Set(derivedData.moves.map(toId));

/** Pokémon whose moves are checked against their newest learnsets instead of Gen 7's (no event restrictions). */
export const NEW_LEARNSET_IDS = new Set([...NEW_BASE_SPECIES, ...UNLOCKED_FORMES].map(toId));

/** Mega Lucario Z's Ability, new in Pokémon Champions (the simulator doesn't have it). */
export const AURA_GUARD = {
  id: 'auraguard',
  name: 'Aura Guard',
  shortDesc: 'This Pokemon takes 1/2 damage from contact moves.',
  desc: 'This Pokemon receives 1/2 damage from moves that make contact. Contact moves used by a Pokemon with Long Reach deal regular damage.',
};

/**
 * Data layered on Showdown's Gen 7 data (as mod data, `inherit: true` entries):
 * the Champions Megas, their stones, the Pokémon, moves and Abilities they need
 * stop being "Future" (Showdown derives that from the entry's generation), and
 * the Megas take Champions' types, Abilities and base stats.
 */
export function championsOverrides() {
  // Fresh objects for every entry: the dex merges parent data into them in place.
  const legal = () => ({ inherit: true, isNonstandard: null, tier: 'OU' });
  const available = () => ({ inherit: true, gen: 7, isNonstandard: null });
  const species: Record<string, object> = {};
  const formatsData: Record<string, object> = {};
  for (const m of CHAMPIONS_MEGAS) {
    species[toId(m.species)] = { inherit: true, gen: 7, types: [...m.types], abilities: { 0: m.ability }, baseStats: { ...m.baseStats } };
    formatsData[toId(m.species)] = legal();
  }
  for (const name of [...NEW_BASE_SPECIES, ...UNLOCKED_FORMES]) {
    species[toId(name)] = { inherit: true, gen: 7 };
    formatsData[toId(name)] = legal();
  }
  const items = Object.fromEntries(CHAMPIONS_STONES.map(n => [toId(n), available()]));
  const moves = Object.fromEntries(NEW_MOVES.map(n => [toId(n), available()]));
  const abilities: Record<string, object> = Object.fromEntries(NEW_ABILITIES.map(n => [toId(n), available()]));
  abilities[AURA_GUARD.id] = {
    name: AURA_GUARD.name, num: 10001, gen: 7, rating: 3.5, flags: { breakable: 1 },
    shortDesc: AURA_GUARD.shortDesc, desc: AURA_GUARD.desc,
  };
  // Eternal Flower Floette was event-only in Gen 6-7; it's a regular Pokémon for Champions purposes.
  const learnsets = Object.fromEntries(UNLOCKED_FORMES.map(n => [toId(n), { inherit: true, eventOnly: false }]));
  return { Species: species, FormatsData: formatsData, Items: items, Moves: moves, Abilities: abilities, Learnsets: learnsets };
}

/** Mod id for Gen 7 + the Champions additions (simulator and UI data). */
export const CHAMPIONS_MOD = 'gen7battletree';
